//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clientes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CLIENTES_BEntities : DbContext
    {
        public CLIENTES_BEntities()
            : base("name=CLIENTES_BEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int SP_CREATE_CLIENTES(string nombre_Cliente, string tipo_Documento, Nullable<decimal> numero_Documento, string dirección, Nullable<decimal> teléfono, string correo, Nullable<System.DateTime> fecha_Creación)
        {
            var nombre_ClienteParameter = nombre_Cliente != null ?
                new ObjectParameter("Nombre_Cliente", nombre_Cliente) :
                new ObjectParameter("Nombre_Cliente", typeof(string));
    
            var tipo_DocumentoParameter = tipo_Documento != null ?
                new ObjectParameter("Tipo_Documento", tipo_Documento) :
                new ObjectParameter("Tipo_Documento", typeof(string));
    
            var numero_DocumentoParameter = numero_Documento.HasValue ?
                new ObjectParameter("Numero_Documento", numero_Documento) :
                new ObjectParameter("Numero_Documento", typeof(decimal));
    
            var direcciónParameter = dirección != null ?
                new ObjectParameter("Dirección", dirección) :
                new ObjectParameter("Dirección", typeof(string));
    
            var teléfonoParameter = teléfono.HasValue ?
                new ObjectParameter("Teléfono", teléfono) :
                new ObjectParameter("Teléfono", typeof(decimal));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var fecha_CreaciónParameter = fecha_Creación.HasValue ?
                new ObjectParameter("Fecha_Creación", fecha_Creación) :
                new ObjectParameter("Fecha_Creación", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_CLIENTES", nombre_ClienteParameter, tipo_DocumentoParameter, numero_DocumentoParameter, direcciónParameter, teléfonoParameter, correoParameter, fecha_CreaciónParameter);
        }
    }
}
